### ISSUE TITLE
疑问。

### ISSUE THREAD

**Issue by kingreatwill** [FollowmeTech/fm.consulinterop#3]
![image](https://user-images.githubusercontent.com/13087689/43299080-6cbedc96-918b-11e8-906c-8e249d8a6508.png)
刚刚做了一个高可用测试，发现只要有服务挂掉就一定会出错

**Comment by lincuss** [comment]
能够再描述清楚下你的测试流程?

**Comment by kingreatwill** [comment]
启动5个srv，client循环hi的方法，随便关闭一个srv，其它四个srv是健康的，一定会出错，

**Comment by lincuss** [comment]
可以启动consulintrop.innerlog 把错误所有的log发出来看看

**Comment by kingreatwill** [comment]
这个错误是因为缓存consul服务地址引起的。关闭服务时没有及时更新缓存地址导致调用了一个挂掉的服务

**Comment by lincuss** [comment]
有一个刷新时间设置的
另外就算意外挂掉了, client就会主动的踢掉这个connection的~~

你可以把你的详细过程,配置,log 发出来看看是否有这个bug
